- name: Installing Mysql and dependencies
  package:
    name:
      - mysql-server
      - mysql-client 
      - python3-mysqldb
      - libmysqlclient-dev
    state: present
    update_cache: yes

- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes
