---
- name: Installing Mysql  and dependencies
  package:
    name:
      - mysql-server
      - mysql-client 
      - python3-mysqldb
      - libmysqlclient-dev
    state: present
    update_cache: yes

- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes

- name: creating medium_db
  mysql_db:
    name: "{{db_name}}"
    state: present

- name: creating mysql user (medium_post)
  mysql_user:
    name: "{{db_user}}"
    password: "{{db_pass}}"
    priv: '*.*:ALL'
    host: '192.168.29.86'
    state: present

- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes

- name: Restart mysql
  shell: systemctl restart mysql
